import { Flex, Theme, ThemePanel } from "@radix-ui/themes";
import "@radix-ui/themes/styles.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Navbar from "./_components/Navbar";
import "./globals.css";
import Provider from "./providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const appPortalId = "app-portal";

    return (
        <html lang="en">
            <body className={inter.className} suppressHydrationWarning>
                <Provider>
                    <Theme accentColor="gold" grayColor="sand" panelBackground="solid">
                        <Flex id={appPortalId} style={{ position: "absolute" }} />
                        <Navbar appPortalId={appPortalId} />
                        {children}
                        <ThemePanel />
                    </Theme>
                </Provider>
            </body>
        </html>
    );
}
